# Generated by Django 6.0 on 2026-01-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('municipality', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_ecological', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.producer'),
        ),
    ]
