# Generated by Django 6.0 on 2026-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producer_product_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('unidad', 'unidad'), ('docena', 'docena'), ('pieza', 'pieza'), ('lote', 'lote'), ('botella', 'botella'), ('tarro', 'tarro')], default='kg', max_length=20),
        ),
    ]
